### **Problem Statement**:
A movie review site needs to create a database to store their data and perform operations on it. You are asked to create a dummy model with 100 users and 1000 movies to explain how it will work

#### Tasks to be performed:
1. Generate 1000 movie IDs starting from 1301
2. Create a matrix, movies_matrix, to store users rating such that
> There are 100 users<br>
> Each user can review as many movies as he/she wants<br>
> The review should be in between 0 to 10 (both inclusive)<br>
   
3. We have ten movie experts, let us take their reviews also. Also, 50 new movies have to be added and their reviews

4. Create, final_movie_rating matrix with four columns i.e., ‘Movie ID’, ‘Average rating’, ‘Number of ratings’, and ‘Standard deviation of ratings’

5. Also convert the final movie ratings to have range from 0 to 10, such that the minimum rating converts to 0 and maximum to 10, and the other values in between

6. Display the films rating-wise, highest to lowest

### Imports

In [ ]:
import numpy as np

In [ ]:
np.set_printoptions(formatter={'float_kind':'{:.3f}'.format})  #Sets the display setting so that all the float values will have 3 values after decimal

### Creating numpy arrays

In [ ]:
#Creating a Single-Dimensional Array

arr = np.array([2,3,7]) #Calling the Array Function
print(arr)
print(arr.shape)

In [ ]:
#Creating a Multi-Dimensional Array

arr = np.array([[10,20,30],[40,50,60]])
print(arr)
print(arr.shape)
print(type(arr))

In [ ]:
#np.empty()
#arr = np.empty([2,2], dtype=complex)
arr = np.empty((2,2), dtype=float) #Returns a new array with specified shape & type filled with random values
print(arr)

In [5]:
X = np.full((2,3), 5) #Returns an array with specified shape & filled with specified value
print(X)

[[5 5 5]
 [5 5 5]]


In [6]:
#np.zeros()

arr = np.zeros((2,3)) #Returns a new array with specified shape filled with zeroes
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#arr = np.ones((3,5)) #Returns a new array with specified shape filled with ones
arr = np.ones((3,5), dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
X = np.eye(5) #returns an array of identity matrix of size 5X5
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
#np.linspace()

arr = np.linspace(0, 20, 10) #Returns a Linearly-Spaced Vector spacing
print(arr)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


### Task 1: Create a NumPy array of 1000 movie IDs starting from 1301

In [12]:
# creating 1000 movie-ids
movie_id = np.arange(1301,2301)
print(movie_id[:10])
movie_id.size

[1301 1302 1303 1304 1305 1306 1307 1308 1309 1310]


1000

In [13]:
print(movie_id[-10:])

[2291 2292 2293 2294 2295 2296 2297 2298 2299 2300]


In [ ]:
# user_id = np.arange(20201,20301)

In [14]:
# creating 100 user-ids (creating a list and creating the np array from the list)
user_id = []
for i in range(20201,20301):
    user_id.append(i)
user_id = np.array(user_id)

In [15]:
print(user_id.size) #checking the number of elements in numpy array
print(user_id.shape)
print(type(user_id))
print(user_id)

100
(100,)
<class 'numpy.ndarray'>
[20201 20202 20203 20204 20205 20206 20207 20208 20209 20210 20211 20212
 20213 20214 20215 20216 20217 20218 20219 20220 20221 20222 20223 20224
 20225 20226 20227 20228 20229 20230 20231 20232 20233 20234 20235 20236
 20237 20238 20239 20240 20241 20242 20243 20244 20245 20246 20247 20248
 20249 20250 20251 20252 20253 20254 20255 20256 20257 20258 20259 20260
 20261 20262 20263 20264 20265 20266 20267 20268 20269 20270 20271 20272
 20273 20274 20275 20276 20277 20278 20279 20280 20281 20282 20283 20284
 20285 20286 20287 20288 20289 20290 20291 20292 20293 20294 20295 20296
 20297 20298 20299 20300]


### Task 2: Create Matrix 1 such that:
>* There are 100 users
>* Each user can review as many movies as he/she wants.
>* The review should be in between 0 to 10 (both inclusive)
>* The movies which are not reviewed by a user should have value -1

In [17]:
import random
movies_rated_by_me = np.full(1000,-1)
#print('movies_rated_by_me:', movies_rated_by_me)
num_movies_rated = random.randint(0,999)
#print('num_movies_rated:',num_movies_rated)
#random.seed(num_movies_rated)
movies_that_i_will_rate = random.sample(range(0,999),num_movies_rated)

In [ ]:
movies_rated_by_me[650] = 8

In [ ]:
movies_rated_by_me = np.full(1000,-1)
#print('movies_rated_by_me:', movies_rated_by_me)
num_movies_rated = random.randint(0,999)
#print('num_movies_rated:',num_movies_rated)
#random.seed(num_movies_rated)
movies_that_i_will_rate = random.sample(range(0,999),num_movies_rated)
#print('movies_that_i_will_rate:', movies_that_i_will_rate)
#user rating for movies they chosed to rate
for index in movies_that_i_will_rate:
    movies_rated_by_me[index] = random.randint(0,10)
#print('movies_rated_by_me:', movies_rated_by_me)
movie_matrix.append(movies_rated_by_me)

In [21]:
import random
movie_matrix = []
for user in range(100):
    #print('user:', user)
    movies_rated_by_me = np.full(1000,-1)
    #print('movies_rated_by_me:', movies_rated_by_me)
    num_movies_rated = random.randint(0,999)
    #print('num_movies_rated:',num_movies_rated)
    #random.seed(num_movies_rated)
    movies_that_i_will_rate = random.sample(range(0,999),num_movies_rated)
    #print('movies_that_i_will_rate:', movies_that_i_will_rate)
    #user rating for movies they chosed to rate
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0,10)
    #print('movies_rated_by_me:', movies_rated_by_me)
    movie_matrix.append(movies_rated_by_me)
#print('movie_matrix:', movie_matrix)
movie_matrix = np.array(movie_matrix)

In [22]:
print('movie_matrix:')
print('Shape:',movie_matrix.shape) #100 users(rows) and 1000 movies(columns)
print('No.of elements:',movie_matrix.size)
print('No.of dimesions',movie_matrix.ndim)

movie_matrix:
Shape: (100, 1000)
No.of elements: 100000
No.of dimesions 2


In [ ]:
movie_matrix[:10, :15]
# movie_matrix

Attributes of the numpy ndarray class

### Task 3: Add the reviews of 10 movie experts and 50 more films

In [23]:
#Expert movie reviews
expert_matrix = []
for user in range(10):
    movies_rated_by_me = np.full(1000,-1)
    num_movies_rated = random.randint(0,999)
    #random.seed(num_movies_rated)
    movies_that_i_will_rate = random.sample(range(0,1000),num_movies_rated)
    #user rating for movies they chosed to rate
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0,10)
    expert_matrix.append(movies_rated_by_me)

expert_matrix = np.array(expert_matrix)


In [24]:
print(expert_matrix.shape)
expert_matrix[:, :15]

(10, 1000)


array([[ 5, -1, -1, -1, -1, -1, -1,  7,  6, -1,  0,  1,  1, -1,  6],
       [-1, -1, -1, -1, -1,  3, -1,  7, -1, -1, -1,  8,  6, -1, -1],
       [ 1,  9,  5,  9,  4,  6,  9,  2, 10,  3, -1,  5,  9,  3, -1],
       [-1, -1,  8,  4, -1,  2, -1,  2,  5,  1, -1,  9, -1,  8,  6],
       [ 7, -1, -1, -1, -1, -1, -1, -1, -1,  4, -1,  1,  9, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [10, -1, -1, -1, -1, -1, -1,  4,  2,  1, -1, -1,  7,  0, -1],
       [ 6, -1,  4,  7,  0,  4, -1,  4,  9,  4, -1,  5,  9,  5, -1],
       [10, -1, -1, -1, -1,  5, -1,  9, -1, -1, -1,  0,  4, -1,  7],
       [ 1, 10,  1,  6,  7,  9,  3,  8, -1,  0, -1,  8,  2,  1,  8]])

In [25]:
#adding these expert reviews with original reviews
movie_matrix = np.vstack([movie_matrix,expert_matrix]) # vstack is used to stack arrays vertically
movie_matrix.shape

(110, 1000)

In [26]:
new_movies_matrix = []
for user in range(110):
    movies_rated_by_me = np.full(50,-1)
    num_movies_rated = random.randint(0,49)
    #random.seed(num_movies_rated)
    movies_that_i_will_rate = random.sample(range(0,50),num_movies_rated)
    #user rating for movies they chosed to rate
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0,10)
    new_movies_matrix.append(movies_rated_by_me)
new_movies_matrix = np.array(new_movies_matrix)

In [27]:
print(new_movies_matrix.shape)
new_movies_matrix[:15, :15]

(110, 50)


array([[ 6,  0,  6, 10, 10,  0, 10,  5,  4, 10,  5,  7,  9,  2, -1],
       [ 3,  1, -1,  3,  8,  3, 10,  9,  7,  6, 10, -1,  5,  1,  7],
       [ 0, -1,  3,  7,  3, -1, -1,  7,  4,  9,  5, -1, -1,  8,  5],
       [ 0,  6,  5, -1,  0,  6,  3, -1,  4,  3,  5,  2, -1,  0, 10],
       [-1, -1,  5, -1,  7, -1, -1, -1,  6,  1,  5,  4,  2, -1, -1],
       [ 8,  9, -1, -1, 10,  2,  8, -1,  4,  4, 10,  9,  2,  7, -1],
       [ 9,  8, -1,  2, -1, -1, -1, -1, -1,  0, -1,  1,  3,  0, -1],
       [-1, -1, -1, -1, -1,  8, -1,  2,  9, -1, -1,  4, -1, -1,  5],
       [-1,  9, -1, -1, -1,  4, -1, -1, -1,  2, -1, -1, -1, -1, -1],
       [ 6, -1, -1, -1, -1,  5, -1, -1,  0, -1, -1, -1,  8, -1, -1],
       [ 0,  1,  9,  6,  8,  2,  2,  7,  3,  0,  8,  5, 10,  4,  2],
       [-1,  1, -1,  7, -1, -1, -1, -1,  6, -1,  3, -1, -1,  0, -1],
       [-1,  8, -1, -1, -1,  3, -1, -1, -1, -1, -1, -1,  6,  7, -1],
       [-1,  1, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 6,  7, -1, -1, -1,  9, -1

In [46]:
new_movies_id = np.append(movie_id,np.arange(2301,2351))
new_movies_id.size

1050

In [28]:
#adding the reviews of new movies with original reviews
movie_matrix = np.hstack([movie_matrix,new_movies_matrix]) # hstack is used to stack arrays horizontally
print(movie_matrix.shape) #100 users + 10 experts(rows) and 1000 + 50 movies(columns)

(110, 1050)


In [29]:
movie_matrix[100:109, 1035:1049]

array([[-1,  2,  3,  4,  8,  0,  3,  2,  2, -1, -1, -1,  0,  6],
       [ 1, -1,  6,  0,  9,  1,  6, -1, -1,  5, -1,  2,  5,  4],
       [ 7, -1, 10,  2, -1,  3,  5, -1, -1,  0,  3,  0, -1,  6],
       [ 4, -1,  6, -1,  8, -1, -1,  7, 10, -1,  9, 10,  4,  5],
       [ 8,  5,  3,  5,  2,  5, 10,  5,  8,  4,  1, -1, -1,  6],
       [ 0,  5, -1, -1, -1,  4,  2,  0, 10,  8, -1,  9, -1,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1,  3,  0,  9,  3,  9,  6,  1, -1,  8,  1, 10,  6,  5]])

We can see now we have 110 users and 1050 movies

#### Indexing and Slicing in NumPy

In [30]:
#Indexing
a = np.arange(10)
print("Accessed Element:",a[5]) #Accessing a Single Element
print(a)

Accessed Element: 5
[0 1 2 3 4 5 6 7 8 9]


In [31]:
#Indexing
a = np.arange(1,10)
print("Accessed Element:",a[5]) #Accessing a Single Element
print(a)

Accessed Element: 6
[1 2 3 4 5 6 7 8 9]


In [32]:
a = np.arange(1,10)
print('Given Array:',a)
print('Retrieved Elements:',a[3:])

Given Array: [1 2 3 4 5 6 7 8 9]
Retrieved Elements: [4 5 6 7 8 9]


In [33]:
a = np.arange(1,10)
print('Given Array:',a)
print('Retrieved Elements:',a[1:7:2])

Given Array: [1 2 3 4 5 6 7 8 9]
Retrieved Elements: [2 4 6]


In [34]:
a = np.arange(1,10)
print('Given Array:',a)
slice1 = slice(2,7,2) #slice() function to access multiple elements
print(type(slice1))
print(a[slice1])
print(a[2:7:2]) #without using slice function

Given Array: [1 2 3 4 5 6 7 8 9]
<class 'slice'>
[3 5 7]
[3 5 7]


In [35]:
#Indexing
arr = np.array([[2,4,5],[6,8,1],[4,1,6],[9,1,4]]) #Creating a Multi-Dimensional Array
print("Original Array:\n", arr)
print(arr[0,1]) #In a 2-dimensional array we can access elements using [rows,column] indexes

Original Array:
 [[2 4 5]
 [6 8 1]
 [4 1 6]
 [9 1 4]]
4


In [36]:
print("Original Array:\n", arr)
print("Sliced Array1:\n",arr[0:3,0:2]) #Slicing the first 3 rows & 2 columns from arr
print("Sliced Array2:\n",arr[:3,:]) #Slicing the first 3 rows
print("Sliced Array3:\n",arr[:,:2]) #Slicing the first 2 columns

Original Array:
 [[2 4 5]
 [6 8 1]
 [4 1 6]
 [9 1 4]]
Sliced Array1:
 [[2 4]
 [6 8]
 [4 1]]
Sliced Array2:
 [[2 4 5]
 [6 8 1]
 [4 1 6]]
Sliced Array3:
 [[2 4]
 [6 8]
 [4 1]
 [9 1]]


In [ ]:
help(np)

#### Statistical Functions in NumPy

In [38]:
#amin() & amax() - Returns the minimum & the maximum from the elements in the given array along the given axis
# Minimum of array, if axis is None; the result is an array of dimension a.ndim – 1, if axis is mentioned

arr = np.array([[5,4,6],[1,3,9],[7,2,8]])
print(arr)


[[5 4 6]
 [1 3 9]
 [7 2 8]]


In [39]:
print(np.amin(arr))
print(np.amin(arr, 0))  # minimum of each column
print(np.amin(arr, 1))  # minimum of each row

1
[1 2 6]
[4 1 2]


In [40]:
print(np.amax(arr))
print(np.amax(arr, 0))  # max of each column
print(np.amax(arr, 1))  # max of each row

9
[7 4 9]
[6 9 8]


In [41]:
arr = np.array([[4,9,2],
              [3,1,2]])
arr

array([[4, 9, 2],
       [3, 1, 2]])

In [42]:
print('mean:',arr.mean())
print('Std dev:',arr.std()) #std() - Returns the Standard Deviation of the given data. It is the square-root of variance
print('min value',arr.min())
print('max value', arr.max())

print('median', np.median(arr))

mean: 3.5
Std dev: 2.6299556396765835
min value 1
max value 9
median 2.5


In [43]:
#mean() - Returns the Mean of the given data

arr = np.array([[0,5,7],
              [4,9,1],
              [3,1,7]])
print(np.mean(arr))

print(np.mean(arr,0)) #Mean along axis - 0 (mean of each column)

print(np.mean(arr,1)) #Mean along axis - 1 (mean of each row)

4.111111111111111
[2.33333333 5.         5.        ]
[4.         4.66666667 3.66666667]


### Task 4:Create average user rating matrix using movies_matrix
The average_user_rating_matrix will have 4 columns:
* ‘Movie ID’
* ‘Average rating’
* ‘Number of ratings’
* ‘Standard deviation of ratings’

In [44]:
# picking up one column which will be the rating of that movie by 110 users
i = 0
m = movie_matrix[:,i]
print(m)
m = m[m>=0]
print(m)

[-1 -1  9 -1 -1 -1  0  6 -1  7  7 -1 -1 -1  1 -1 -1 -1  4  7 -1  4  5  2
  9 -1  8  1 -1 -1 -1 10  8  5 -1  1 -1 -1  8  5  0 -1  0 10 -1 -1 -1 -1
 -1 -1  4 10  0  2  5 -1  3  4  6  9  8  8  7 -1 -1 -1  4 -1 -1 -1  5  0
  5 -1 -1 -1 -1  1 -1  6 -1  7 -1  7  4  8  8 -1 -1  0 -1  2 -1 -1 -1  8
 -1 -1 -1  0  5 -1  1 -1  7 -1 10  6 10  1]
[ 9  0  6  7  7  1  4  7  4  5  2  9  8  1 10  8  5  1  8  5  0  0 10  4
 10  0  2  5  3  4  6  9  8  8  7  4  5  0  5  1  6  7  7  4  8  8  0  2
  8  0  5  1  7 10  6 10  1]


In [47]:
final_movie_rating = []
total_num_rating = m.size
rating = m.mean()
standard_deviation = m.std()
final_movie_rating.append([new_movies_id[i],rating,total_num_rating,standard_deviation])
final_movie_rating

[[1301, 5.052631578947368, 57, 3.203184011516408]]

In [48]:
# putting the above together in a a loop
final_movie_rating = []
for i in range(1050):
    #each movie's rating
    m = movie_matrix[:,i] # basically picking up one column at a time, which will be rating of that movie by all 110 users
    m = m[m>=0]
    #total_rate = m.sum()
    total_num_rating = m.size
    rating = m.mean()
    standard_deviation = m.std()
    final_movie_rating.append([new_movies_id[i],rating,total_num_rating,standard_deviation])

In [49]:
final_movie_rating = np.array(final_movie_rating)
final_movie_rating

array([[1301.        ,    5.05263158,   57.        ,    3.20318401],
       [1302.        ,    5.77272727,   44.        ,    3.2673567 ],
       [1303.        ,    5.5       ,   54.        ,    3.04746403],
       ...,
       [2348.        ,    4.5       ,   54.        ,    3.10763695],
       [2349.        ,    4.94444444,   54.        ,    3.26834802],
       [2350.        ,    5.22641509,   53.        ,    3.06311908]])

#### Mathematical operation using NumPy

In [ ]:
#add() - Used to add arguments element-wise

a = np.array([[2,0],
              [4,9]])
b = np.array([[2,0],
              [4,9]])
print(a)
print(b)

In [ ]:
print(np.add(a,b))


In [ ]:
print("Another way to perform element-wise operation\n",a+b)
print("1 added to Matrix 'a' element-wise\n ",a+1)

In [ ]:
#subtract() - Used to subtract arguments element-wise

a = np.array([[10,20,30]])
b = np.array([[10,10,10]])
np.subtract(a,b)


In [ ]:
#multiply() - Used to add multiply arguments element-wise

a = np.array([[0,5,7],
              [4,9,1],
              [3,1,7]])
b = np.array([[10,10,10]])
np.multiply(a,b)

In [ ]:
#multiply() - Used to add multiply arguments element-wise

a = np.array([[0,5,7],
              [4,9,1],
              [3,1,7]])
b = np.array([[10,10,10],
              [2, 2, 2 ],
              [5, 5, 5]])
np.multiply(a,b)

In [ ]:
#divide() - Used to divide arguments element-wise

a = np.array([[20,24,32],
              [4,8,18],
              [2,54,78]])
b = np.array([[2]])
np.divide(a,b)

In [ ]:
#around() - Used to round off the array elements

arr = [7.52, 21.58, 42.81, 43.72, 14.23, 32.64, 51.91, 2.50, 1.99, 56.65, 55.00]
print("Input array : \n",arr)

print ("\nRounded values : \n",np.around(arr))
print ("\nRounded values after decimal 1 : \n",np.around(arr,1))
print ("\nRounded values before decimal 1: \n",np.around(arr,-1))

In [ ]:
#floor() - Returns the greatest of integers present in the array but not not more than the input parameter

arr = [7.5, 21.5, 42.8, 43.7, 14.2, 32.6, 51.9, 2.5, 1.9]
print("Input array : \n",arr)

print("Floored Values:\n",np.floor(arr))

In [ ]:
#ceil() -Returns the ceiling of an input value

arr = [7.5, 21.5, 42.8, 43.7, 14.2, 32.6, 51.9, 2.5, 1.9]
print("Input array : \n",arr)

print("Ceiling Values:\n",np.ceil(arr))

### Task 5: Convert the final average movie ratings to range from 0 to 10
The minimum rating converts to 0 and maximum to 10 , and the other values in between

In [ ]:
#Converting the average of movie ratings to have the range 0 to 10
x = final_movie_rating[:,1]
old_range = x.max()-x.min()
new_range = (10 - 0)
final_movie_rating[:,1] = ((x - x.min())*(new_range/old_range) + 0)

In [ ]:
final_movie_rating

In [ ]:
final_movie_rating.shape

#### numpy.argsort
* Using numpy.argsort() in descending order returns the indicies of the highest n values in a numpy.array.
* USE LIST SLICING TO USE NUMPY ARGSORT IN DESCENDING ORDER
* Use numpy.argsort(an_array) to sort the indices of an_array in ascending order. Use the syntax ranked[::-1] with ranked as the previous result to reverse ranked

In [ ]:
arr = np.array([ 31, 5,  8, 21, 15, 18, 9])
print ("Original unsorted array: ", arr)
arr_index_sorted = np.argsort(arr)
print ("Sorted indices : ", arr_index_sorted)
print("Sorted array : ", arr[arr_index_sorted])

In [ ]:
arr = np.array([ 31, 5,  8, 21, 15, 18, 9])
print ("Original unsorted array: ", arr)
arr_index_sorted = arr.argsort()
print ("Sorted indices ascending: ", arr_index_sorted)
arr_index_sorted = arr.argsort()[::-1]
print ("Sorted indices descending : ", arr_index_sorted)
print("Sorted array descending : ", arr[arr_index_sorted])

In [ ]:
final_movie_rating

In [ ]:
final_movie_rating[:,1].argsort()[::-1]

In [ ]:
sorted_films = final_movie_rating[final_movie_rating[:,1].argsort()[::-1]]

In [ ]:
print(sorted_films)

#### numpy.savetxt() method is used to write files from a numpy array

In [50]:
# np.savetxt('ranked_movie_data.csv',sorted_films, delimiter=',')
np.savetxt('ranked_movie_data.csv',movie_matrix, delimiter=',')

#### numpy.genfromtxt() method is used to read files in a numpy array

In [ ]:
data = np.genfromtxt('ranked_movie_data.csv',delimiter = ',')
#data = np.genfromtxt('/content/ranked_movie_data.csv',delimiter = ',')

In [ ]:
data

### [Learn more about NumPy](https://numpy.org/devdocs/user/quickstart.html)